name: iOS Build

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'

    - name: Build WebRTCiOSSDK
      run: xcodebuild -scheme WebRTCiOSSDK -configuration Release  -destination "generic/platform=iOS" ARCHS=arm64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build

    - name: Build WebRTCSampleApp
      run: xcodebuild -scheme WebRTC-Sample-App -configuration Release  -destination "generic/platform=iOS" ARCHS=arm64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build